You are given cricket dataset with information collected about real ODI matches played over past few years. 
Since you are a data scientist, you decided to apply for a role in BCCI and help India with strategies to win a match.

The first innings has been played and target is 300 to be chased by India.

1. What is the best strategy (run rate) for first 10 overs to win the match? Justify and support your answer with empirical evidence.

2. Currently India is at 50-2 (50 runs and lost 2 wickets) at the end of 10 overs. What is the best strategy for 11-20 overs?

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('04_cricket_1999to2011.csv')

In [4]:
df

,Match,Date,Innings,Over,Runs,Total.Runs,Innings.Total.Runs,Runs.Remaining,Total.Out,Innings.Total.Out,...,at.bat.won.toss,at.bat.at.home,at.bat.bat.first,chose_bat_1st,chose_bat_2nd,forced_bat_1st,forced_bat_2nd,new.game,Error.In.Data,common.support
0,65193,14/05/1999,1,1,4,4,204,200,0,10,...,0,0,1,0,0,1,0,1,0,1
1,65193,14/05/1999,1,2,2,6,204,198,0,10,...,0,0,1,0,0,1,0,0,0,1
2,65193,14/05/1999,1,3,3,9,204,195,0,10,...,0,0,1,0,0,1,0,0,0,1
3,65193,14/05/1999,1,4,2,20,204,184,0,10,...,0,0,1,0,0,1,0,0,0,1
4,65193,14/05/1999,1,5,6,37,204,167,0,10,...,0,0,1,0,0,1,0,0,0,1
5,65193,14/05/1999,1,6,3,40,204,164,0,10,...,0,0,1,0,0,1,0,0,0,1
6,65193,14/05/1999,1,7,2,42,204,162,1,10,...,0,0,1,0,0,1,0,0,0,1
7,65193,14/05/1999,1,8,1,43,204,161,1,10,...,0,0,1,0,0,1,0,0,0,1
8,65193,14/05/1999,1,9,7,50,204,154,1,10,...,0,0,1,0,0,1,0,0,0,1
9,65193,14/05/1999,1,10,0,50,204,154,2,10,...,0,0,1,0,0,1,0,0,0,1
10,65193,14/05/1999,1,11,4,54,204,150,2,10,...,0,0,1,0,0,1,0,0,0,1
11,65193,14/05/1999,1,12,2,56,204,148,2,10,...,0,0,1,0,0,1,0,0,0,1
12,65193,14/05/1999,1,13,7,63,204,141,3,10,...,0,0,1,0,0,1,0,0,0,1
13,65193,14/05/1999,1,14,1,64,204,140,4,10,...,0,0,1,0,0,1,0,0,0,1
14,65193,14/05/1999,1,15,1,65,204,139,5,10,...,0,0,1,0,0,1,0,0,0,1
15,65193,14/05/1999,1,16,4,69,204,135,5,10,...,0,0,1,0,0,1,0,0,0,1
16,65193,14/05/1999,1,17,7,76,204,128,5,10,...,0,0,1,0,0,1,0,0,0,1
17,65193,14/05/1999,1,18,9,85,204,119,5,10,...,0,0,1,0,0,1,0,0,0,1
18,65193,14/05/1999,1,19,7,92,204,112,5,10,...,0,0,1,0,0,1,0,0,0,1
19,65193,14/05/1999,1,20,8,100,204,104,5,10,...,0,0,1,0,0,1,0,0,0,1
20,65193,14/05/1999,1,21,7,107,204,97,5,10,...,0,0,1,0,0,1,0,0,0,1
21,65193,14/05/1999,1,22,4,111,204,93,5,10,...,0,0,1,0,0,1,0,0,0,1
22,65193,14/05/1999,1,23,9,120,204,84,5,10,...,0,0,1,0,0,1,0,0,0,1
23,65193,14/05/1999,1,24,2,122,204,82,5,10,...,0,0,1,0,0,1,0,0,0,1
24,65193,14/05/1999,1,25,3,125,204,79,5,10,...,0,0,1,0,0,1,0,0,0,1
25,65193,14/05/1999,1,26,3,128,204,76,5,10,...,0,0,1,0,0,1,0,0,0,1
26,65193,14/05/1999,1,27,0,128,204,76,5,10,...,0,0,1,0,0,1,0,0,0,1
27,65193,14/05/1999,1,28,2,132,204,72,5,10,...,0,0,1,0,0,1,0,0,0,1
28,65193,14/05/1999,1,29,14,146,204,58,5,10,...,0,0,1,0,0,1,0,0,0,1
29,65193,14/05/1999,1,30,3,149,204,55,6,10,...,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126738,536933,11/12/2011,2,15,6,71,233,162,4,10,...,0,0,0,0,0,0,1,0,0,1
126739,536933,11/12/2011,2,16,7,78,233,155,5,10,...,0,0,0,0,0,0,1,0,0,1
126740,536933,11/12/2011,2,17,2,80,233,153,5,10,...,0,0,0,0,0,0,1,0,0,1
126741,536933,11/12/2011,2,18,12,92,233,141,5,10,...,0,0,0,0,0,0,1,0,0,1
126742,536933,11/12/2011,2,19,7,99,233,134,5,10,...,0,0,0,0,0,0,1,0,0,1
126743,536933,11/12/2011,2,20,5,104,233,129,5,10,...,0,0,0,0,0,0,1,0,0,1
126744,536933,11/12/2011,2,21,7,111,233,122,5,10,...,0,0,0,0,0,0,1,0,0,1
126745,536933,11/12/2011,2,22,9,120,233,113,5,10,...,0,0,0,0,0,0,1,0,0,1
126746,536933,11/12/2011,2,23,3,123,233,110,5,10,...,0,0,0,0,0,0,1,0,0,1
126747,536933,11/12/2011,2,24,15,138,233,95,5,10,...,0,0,0,0,0,0,1,0,0,1
126748,536933,11/12/2011,2,25,2,140,233,93,5,10,...,0,0,0,0,0,0,1,0,0,1
126749,536933,11/12/2011,2,26,11,151,233,82,5,10,...,0,0,0,0,0,0,1,0,0,1
126750,536933,11/12/2011,2,27,9,160,233,73,5,10,...,0,0,0,0,0,0,1,0,0,1
126751,536933,11/12/2011,2,28,4,164,233,69,5,10,...,0,0,0,0,0,0,1,0,0,1
126752,536933,11/12/2011,2,29,3,167,233,66,6,10,...,0,0,0,0,0,0,1,0,0,1
126753,536933,11/12/2011,2,30,6,173,233,60,6,10,...,0,0,0,0,0,0,1,0,0,1
126754,536933,11/12/2011,2,31,7,180,233,53,6,10,...,0,0,0,0,0,0,1,0,0,1
126755,536933,11/12/2011,2,32,1,181,233,52,6,10,...,0,0,0,0,0,0,1,0,0,1
126756,536933,11/12/2011,2,33,1,182,233,51,7,10,...,0,0,0,0,0,0,1,0,0,1
126757,536933,11/12/2011,2,34,4,186,233,47,7,10,...,0,0,0,0,0,0,1,0,0,1
126758,536933,11/12/2011,2,35,3,189,233,44,7,10,...,0,0,0,0,0,0,1,0,0,1
126759,536933,11/12/2011,2,36,5,194,233,39,7,10,...,0,0,0,0,0,0,1,0,0,1
126760,536933,11/12/2011,2,37,1,195,233,38,8,10,...,0,0,0,0,0,0,1,0,0,1
126761,536933,11/12/2011,2,38,2,197,233,36,8,10,...,0,0,0,0,0,0,1,0,0,1
126762,536933,11/12/2011,2,39,1,198,233,35,8,10,...,0,0,0,0,0,0,1,0,0,1
126763,536933,11/12/2011,2,40,13,211,233,22,8,10,...,0,0,0,0,0,0,1,0,0,1
126764,536933,11/12/2011,2,41,1,212,233,21,8,10,...,0,0,0,0,0,0,1,0,0,1
126765,536933,11/12/2011,2,42,1,213,233,20,9,10,...,0,0,0,0,0,0,1,0,0,1
126766,536933,11/12/2011,2,43,11,224,233,9,9,10,...,0,0,0,0,0,0,1,0,0,1
126767,536933,11/12/2011,2,44,9,233,233,0,9,10,...,0,0,0,0,0,0,1,0,0,1